language: bash
sudo: required

addons:
  apt:
    packages:
      - ansible

install:
  - pyenv install 2.7.12

script:
  - python --version
  - ansible --version
  - ansible-playbook -i hosts/local ansible.yml
  - hash -r
  - ansible --version
