- hosts: all
  become: yes

  vars:
    rvm1_rubies:
      - "ruby-2.3.1"
    nodejs_version: "4.4"

  tasks:
    # for debian / ubuntu
    - shell: echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" > /etc/apt/sources.list.d/docker.list
      when: "ansible_os_family == 'Debian'"

    - shell: apt-cache policy docker-engine
      when: "ansible_os_family == 'Debian'"

    - apt: name=docker.io state=removed

    - name: install apt packages
      apt: name={{ item }} state=latest
      with_items:
        - build-essential
        - git
        - vim
        - tmux
        - libfontconfig1-dev
        - fish
        - docker-engine
      when: "ansible_os_family == 'Debian'"

  roles:
    - golang
    - { role: rvm_io.rvm1-ruby, tags: ruby, become: yes } # Ruby
    - nodesource.node # Node.js
