- hosts: all
  become: yes
  tags:
    - always
  tasks:
    - shell: "echo 'Defaults env_keep += \"PATH\"' > /etc/sudoers.d/env_keep"
    - shell: "echo 'Defaults secure_path = /sbin:/bin:/usr/sbin:/usr/local/bin:/usr/bin' > /etc/sudoers.d/secure_path"
    - yum: package={{item}} state=latest
      with_items:
        - make
        - gcc
        - git

- hosts: all
  become: yes
  tags:
    - lang
    - node
  tasks:
    - stat: path=/opt/node-v6.9.1-linux-x64
      register: node_src
    - shell: "curl -L https://nodejs.org/dist/v6.9.1/node-v6.9.1-linux-x64.tar.xz | tar -C /opt -Jxf -"
      when: not node_src.stat.exists
    - shell: "echo 'export PATH=/opt/node-v6.9.1-linux-x64/bin:$PATH' > /etc/profile.d/node.sh"

- hosts: all
  become: yes
  tags:
    - lang
    - ruby
  tasks:
    - stat: path=/opt/ruby-2.3.3
      register: ruby_src
    - shell: "curl -L https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.3.tar.gz | tar -C /opt -zxf -"
      when: not ruby_src.stat.exists
    - yum: package={{item}} state=latest
      with_items:
        - zlib-devel
        - openssl-devel
    - shell: make clean && ./configure --enable-shared --prefix=/usr/local && make -j4 && make install
        chdir=/opt/ruby-2.3.3
    - shell: cd /opt/ruby-2.3.3/ext/{{item}} && ruby extconf.rb
      with_items:
        - zlib
        - openssl
    - shell: make clean && ./configure --enable-shared --prefix=/usr/local && make -j4 && make install
        chdir=/opt/ruby-2.3.3
- hosts: all
  become: yes
  tags:
    - lang
    - ruby
    - ruby-user
  tasks:
    - shell: "echo 'export GEM_HOME=$HOME/.gem/ruby/2.3.0' > /etc/profile.d/ruby.sh"
    - shell: "echo 'export PATH=$GEM_HOME/bin:$PATH' >> /etc/profile.d/ruby.sh"
- hosts: all
  tags:
    - lang
    - ruby
    - ruby-user
  tasks:
    - shell: gem install bundler
