- hosts: all
  become: yes
  tasks:
    - stat: path=/opt/node-v6.9.1-linux-x64
      register: node
    - shell: "curl -L https://nodejs.org/dist/v6.9.1/node-v6.9.1-linux-x64.tar.xz | tar -C /opt -Jxf -"
      when: not node.stat.exists
    - stat: path=/etc/profile.d/node.sh
      register: node_env
    - shell: "echo 'export PATH=/opt/node-v6.9.1-linux-x64/bin:$PATH' > /etc/profile.d/node.sh"
      when: not node_env.stat.exists
