- apt: name=python-pip state=latest
  when: "ansible_os_family == 'Debian'"
- shell: pip install -U setuptools

- shell: git clone --depth 1 --single-branch --branch v2.1.0.0-1 https://github.com/ansible/ansible.git /usr/src/ansible
- shell: git submodule update --init
  args:
    chdir: /usr/src/ansible

- shell: make install
  args:
    chdir: /usr/src/ansible

- apt: name=ansible state=absent
  when: "ansible_os_family == 'Debian'"
